const usersData = [
  {
    id: 1,
    username: "Ali Mahmodi",
    image: "assets/images/user.png",
    email: "Ali@google.com",
    skill: "Front-End",
    status: "active",
    transaction: 24.45,
  },
  {
    id: 2,
    username: "Ali Mahmodi",
    image: "assets/images/user.png",
    email: "Ali@google.com",
    skill: "Front-End",
    status: "active",
    transaction: 24.45,
  },
  {
    id: 3,
    username: "Ali Mahmodi",
    image: "assets/images/user.png",
    email: "Ali@google.com",
    skill: "Front-End",
    status: "active",
    transaction: 17.15,
  },
  {
    id: 4,
    username: "Ronak Gholami",
    image: "assets/images/user.png",
    email: "Ronak@google.com",
    skill: "Web Developer",
    status: "active",
    transaction: 24.45,
  },
  {
    id: 5,
    username: "Ali Karimi",
    image: "assets/images/user.png",
    email: "Ali@google.com",
    skill: "Web Developer",
    status: "non-active",
    transaction: 24.45,
  },
  {
    id: 6,
    username: "Sara Asadi",
    image: "assets/images/user.png",
    email: "Sara@google.com",
    skill: "Web Developer",
    status: "active",
    transaction: 78.09,
  },
];

export { usersData };
